# SwiftLint configuration
disabled_rules:
  - trailing_whitespace
  - line_length
  - trailing_comma # Trailing commas are actually good practice in Swift
  - type_body_length # Allow longer class/struct bodies for complex implementations
  - file_length # Allow longer files for complex implementations
  - function_body_length # Allow longer function bodies for complex functions

included:
  - ios/Sources
  - ios/Tests

excluded:
  - ios/Package.swift
